### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MatthijsBurgh** [ros-infrastructure/catkin-sphinx#14]
@wjwwood could you please release a new version which includes the fixes of #12?

As right now this package is broken for Sphinx 4. Which is probably the cause for the broken documentation of `catkin` (https://github.com/ros/catkin/issues/1169).

I tested documentation generation of `catkin` with the current master of this package, which succeeded.

**Comment by wjwwood** [comment]
`0.3.2` should be generally available now.
